### ISSUE TITLE
Segmentation fault with quad precision

### ISSUE THREAD

**Issue by yonggwi** [anishida/lis#10]
I found that quad precision calculation stop when we choose "-initx_zeros 0" which mean user-defined initial vector. 

for instance, we can reproduce it when execute a following example with some options.

./test5 200 2.0 -f quad -initx_zeros 0 

Also I found that we can fix this problem  by adding 

xx = solver->x ;

to  around 926 line (in function lis_solver_get_initial_residual() ) of src/solver/lis_solver.c . I think the problem was due to that a variable xx is not properly initialized. However  I am not so sure whether this prescription is valid or not.
I was wondering if you could give me some advice. 
Thanks in advance.

Yonggwi Cho

**Comment by anishida** [comment]
Hi,

Thank you for your notice.
As you pointed out, xx must be predefined.
Please check 1.6.29, in which the bug is fixed.

Sincerely,
Akira Nishida

**Comment by anishida** [comment]
We have fixed your name in ChangeLog.
Thank you again for your cooperation.

Sincerely,
Akira Nishida

-----Original Message-----
From: Akira NISHIDA [mailto:dolce@yo.rim.or.jp] 
Sent: Friday, October 7, 2016 6:06 PM
To: 'anishida/lis' <reply@reply.github.com>; 'anishida/lis' <lis@noreply.github.com>
Subject: RE: [anishida/lis] Segmentation fault with quad precision (#10)

Hi,

Thank you for your notice.
As you pointed out, xx must be predefined.
Please check 1.6.29, in which the bug is fixed.

Sincerely,
Akira Nishida

**Comment by yonggwi** [comment]
Thanks a lot!

Sincerely,
Yonggwi Cho
