### ISSUE TITLE
lsolve: singular error

### ISSUE THREAD

**Issue by Konstantin8105** [anishida/lis#18]
Dear, @anishida 

I run `lsolve` with option 0 with next input data:
```
%%MatrixMarket matrix coordinate real general
2 2 4 1 0
1 1 1.0000000000000000e+00
1 2 2.0000000000000000e+00
2 1 1.0000000000000001e-30
2 2 1.0000000000000001e-30
1 3.0000000000000000e+00
2 2.0000000000000002e-30
```
or
```
[ 1      2     ] [x1] = [ 3     ]
[ 1e-30  1e-30 ] [x2]   [ 2e-30 ]
```
Theoretical solution is `x1 = 1`, `x2 = 1`, but result is:
```
%%MatrixMarket vector coordinate real general
2
1   3.00000000000000000000e+00
2   2.00000000000000016667e-30
```
Rhistory:
```
1.000000e+00
3.333333e-31
```

Output:
```
number of processes = 1
matrix size = 2 x 2 (4 nonzero entries)

initial vector x      : all components set to 0
precision             : double
linear solver         : BiCG
preconditioner        : none
convergence condition : ||b-Ax||_2 <= 1.0e-12 * ||b-Ax_0||_2
matrix storage format : CSR
linear solver status  : normal end

BiCG: number of iterations = 1
BiCG:   double             = 1
BiCG:   quad               = 0
BiCG: elapsed time         = 1.790524e-04 sec.
BiCG:   preconditioner     = 2.145767e-06 sec.
BiCG:     matrix creation  = 9.536743e-07 sec.
BiCG:   linear solver      = 1.769066e-04 sec.
BiCG: relative residual    = 3.333333e-31
```

I expect some error about singular matrix.

*Why it is happen?*

If we get min and max absolute non-zero value of matrix, then we will have [min=1e-30 max=2], but type `double` can give to us only 10 numbers after point(mantissa). So we cannot use any of arithmetic operations between that numbers and this is the reason for error.

Could you clarify your point of view.

Thank you for attention.

**Comment by anishida** [comment]
Hi,

Thank you for your question.
Because 2e-30 cannot be handled properly by the double precision, 
the obtained results cannot be trusted.
If you must handle such numbers, please consider to use option 
--enable-longdouble.

Sincerely,
Akira Nishida

**Comment by anishida** [comment]
Hi,

You can also resolve the problem by replacing e-30 with e-10, for example.
In this case, the numbers are larger the tolerance of the solver (1.0e-12)
and we have a correct solution:

1   1.00000000000000044409e+00
2   9.99999999999999777955e-01

Sincerely,
Akira Nishida

-----Original Message-----
From: Akira NISHIDA [mailto:dolce@yo.rim.or.jp] On Behalf Of nishida@kyudai.jp
Sent: Saturday, September 22, 2018 7:37 AM
To: 'anishida/lis' <reply@reply.github.com>; 'anishida/lis' <lis@noreply.github.com>
Cc: 'Akira Nishida' <nishida@ssisc.org>; 'Mention' <mention@noreply.github.com>
Subject: RE: [anishida/lis] lsolve: singular error (#18)

Hi,

Thank you for your question.
Because 2e-30 cannot be handled properly by the double precision, the obtained results cannot be trusted.
If you must handle such numbers, please consider to use option --enable-longdouble.

Sincerely,
Akira Nishida

**Comment by anishida** [comment]
Hi,

Please note that it does not depend on the mantissa but on the tolerance 
of the solver.
If you replace e-30 with e-13 instead, we have a following answer:

%%MatrixMarket vector coordinate real general
2
1   2.99999999999959943153e+00
2   1.99999999999973348887e-13

Sincerely,
Akira Nishida

-----Original Message-----
From: Akira NISHIDA [mailto:dolce@yo.rim.or.jp] On Behalf Of nishida@kyudai.jp
Sent: Monday, September 24, 2018 10:00 AM
To: nishida@kyudai.jp; 'anishida/lis' <reply@reply.github.com>; 'anishida/lis' <lis@noreply.github.com>
Cc: 'Akira Nishida' <nishida@ssisc.org>; 'Mention' <mention@noreply.github.com>
Subject: RE: [anishida/lis] lsolve: singular error (#18)

Hi,

You can also resolve the problem by replacing e-30 with e-10, for example.
In this case, the numbers are larger the tolerance of the solver (1.0e-12) and we have a correct solution:

1   1.00000000000000044409e+00
2   9.99999999999999777955e-01

Sincerely,
Akira Nishida

-----Original Message-----
From: Akira NISHIDA [mailto:dolce@yo.rim.or.jp] On Behalf Of nishida@kyudai.jp
Sent: Saturday, September 22, 2018 7:37 AM
To: 'anishida/lis' <reply@reply.github.com>; 'anishida/lis' <lis@noreply.github.com>
Cc: 'Akira Nishida' <nishida@ssisc.org>; 'Mention' <mention@noreply.github.com>
Subject: RE: [anishida/lis] lsolve: singular error (#18)

Hi,

Thank you for your question.
Because 2e-30 cannot be handled properly by the double precision, the obtained results cannot be trusted.
If you must handle such numbers, please consider to use option --enable-longdouble.

Sincerely,
Akira Nishida

**Comment by Konstantin8105** [comment]
Dear @anishida ,
I agree with your experiments to show calculation limit of floating point arithmetic.(I think, using mantissa by myself is not correct).
My main point of that issue only about 2 allowable result for that case: correct solution or error. Now, result is confuse myself - without error with not correct result.




*Just for information.Example: How create correct solution?*
min and max absolute non-zero value of matrix for:
1) first   row with vector b is -> [1 3]
Check of mantissa: 1/3 < 1e-10 - ok.
2) second  row with vector b is -> [1e-30 2e-30]
Check of mantissa: 1e-30/2e-30 < 1e-10 - ok. (if it is not ok, then generate error).

Let's choose min absolute non-zero value is 1 for each rows.
first row no need to do anything.
Second row - need multiply row of A and row in b by 1/1e-30.

After that - all is will be ok.
```
[ 1      2     ] [x1] = [ 3     ]
[ 1      1     ] [x2]   [ 2     ]
```

**Comment by Konstantin8105** [comment]
Hello,
I will add that checking in my part of software for avoid change `lis`.
Thank you for your attention and thanks for that project.

**Comment by anishida** [comment]
Hi,

As we can see if we replace e-30 with e-13, the error is smaller than 
the tolerance but not exactly zero. 
In such cases, the solver interprets by mistake a local extremum as the 
global one, because the error is smaller than the tolerance.

Sincerely,
Akira Nishida
