### ISSUE TITLE
make check:  checking SAAMG preconditioner error

### ISSUE THREAD

**Issue by zhf-0** [anishida/lis#40]
There are two issues when I install and test the `main` branch. 

The first issue happens during `make`.  My environment is:
- `system`:  `ubuntu 24.04 LTS`
- `gcc`:  `gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0`
- `mpi`: `openmpi-4.1.6`

and my configuration  is 
```
./configure --prefix=$HOME/software/lis/install/ --enable-saamg --enable-mpi
```
The make error message is
```
lis_m_solver_SR2.F90:111:23:

  111 |        call MPI_ISEND (WS(istart+1), inum, LIS_MPI_INTEGER,       &
      |                       1
......
  214 |        call MPI_ISEND (WS(istart + 1), inum, MPI_DOUBLE_PRECISION,     &
      |                       2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
lis_m_solver_SR2.F90:121:23:

  121 |        call MPI_IRECV (WR(istart+1), inum, LIS_MPI_INTEGER,        &
      |                       1
......
  225 |        CALL MPI_IRECV (WR(istart + 1), inum, MPI_DOUBLE_PRECISION,     &
      |                       2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
```
According to [fortran: Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(8)/INTEGER(2))](https://stackoverflow.com/questions/69686755/fortran-error-type-mismatch-between-actual-argument-at-1-and-actual-argument), this issue is fixed by adding `-fallow-argument-mismatch`  to the `FCFLAGS`. 

By the way, I also try to use `gcc-9.3.0+openmpi-4.1.2` to compile the library, and there is no such error message.

The second issue happens during `make check`, and the error message is
```
checking SAAMG preconditioner...

number of processes = 2
matrix size = 100 x 100 (460 nonzero entries)

STOP timer error!!
STOP timer error!!
 timer error...:           1   0.0000000000000000     
 timer error...:           1   0.0000000000000000     
```
The same error happens when I run the command `make check` based on the `gcc-9.3.0+openmpi-4.1.2` compiler.

**Comment by anishida** [comment]
Hi,

 

Thank you for your information.

I tried to include “-fallow-argument-mismatch” to FCFLAGS, but it caused “gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’” when making in my environment (gcc4).

I wish I had a good solution.

 

Sincerely,

Akira Nishida

 

From: zhf-0 ***@***.*** 
Sent: Monday, September 9, 2024 12:19 PM
To: anishida/lis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [anishida/lis] make check: checking SAAMG preconditioner error (Issue #40)

 

There are two issues when I install and test the main branch.

The first issue happens during make. My environment is:

*	system: ubuntu 24.04 LTS
*	gcc: gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
*	mpi: openmpi-4.1.6

and my configuration is

./configure --prefix=$HOME/software/lis/install/ --enable-saamg --enable-mpi

The make error message is

lis_m_solver_SR2.F90:111:23:
 
  111 |        call MPI_ISEND (WS(istart+1), inum, LIS_MPI_INTEGER,       &
      |                       1
......
  214 |        call MPI_ISEND (WS(istart + 1), inum, MPI_DOUBLE_PRECISION,     &
      |                       2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
lis_m_solver_SR2.F90:121:23:
 
  121 |        call MPI_IRECV (WR(istart+1), inum, LIS_MPI_INTEGER,        &
      |                       1
......
  225 |        CALL MPI_IRECV (WR(istart + 1), inum, MPI_DOUBLE_PRECISION,     &
      |                       2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).

According to fortran: Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(8)/INTEGER(2)) <https://stackoverflow.com/questions/69686755/fortran-error-type-mismatch-between-actual-argument-at-1-and-actual-argument> , this issue is fixed by adding -fallow-argument-mismatch to the FCFLAGS.

By the way, I also try to use gcc-9.3.0+openmpi-4.1.2 to compile the library, and there is no such error message.

The second issue happens during make check, and the error message is

checking SAAMG preconditioner...
 
number of processes = 2
matrix size = 100 x 100 (460 nonzero entries)
 
STOP timer error!!
STOP timer error!!
 timer error...:           1   0.0000000000000000     
 timer error...:           1   0.0000000000000000     

The same error happens when I run the command make check based on the gcc-9.3.0+openmpi-4.1.2 compiler.

**Comment by zhf-0** [comment]
Thank you very much for your reply. 

The compiler `gcc-9.3.0` doesn't need the FCFLAGS `-fallow-argument-mismatch` either, let alone the older compiler `gcc4`. Maybe the flag is only needed by newer version of `gcc`.

The flag issue is not important,  while the SAAMG preconditioner is the key to this issue. Have you tried to  run `make check` with the configuration `--enable-saamg`?

**Comment by zhf-0** [comment]
Thank you very much for your patience. I will close this issue.
